
game: main.cpp game.cpp Game/Board/board.cpp Game/Tetramino/tetramino.cpp Game/constants.cpp Game/Menu/menu.cpp Game/Score/score.cpp
	g++ main.cpp game.cpp Game/Board/board.cpp Game/Tetramino/tetramino.cpp Game/constants.cpp Game/Menu/menu.cpp Game/Score/score.cpp -o Gioco -lncurses
